/accept_satisficing_action_server:
  ros__parameters:
    axes:
      - /validity
    thresholds:
      - 0.5
/take_best_action_server:
  ros__parameters:
    n: 1
    random_ties: true
/order_lexicographical_action_server:
  ros__parameters:
    axis_ordering: 
      - '/validity'
/update_cues_prolog_action_server:
  ros__parameters:
    iter_add: 0
    reuse: false
/update_alternatives_prolog_action_server:
  ros__parameters:
    capacity: 0
    keep_policy: none
