# # An optional requirement on the Concept (phenomenon class) of a modelet.
# string concept
# 
# # An optional requirement on the Formalism of a modelet (how it is described).
# string formalism
# 
# # An optional requirement on the Location of a modelet (how it is situated in
# # time and space).
# string location
# 
# 
# # An optional requirement on the Extent of a modelet (how it covers time and
# # space, such as an Area/Volume/Duration).
# string extent
# 
# # An optional requirement on the Creator of a modelet (the engine that created it).
# string creator
# 
# # An optional requirement on membership in a template_set, by template_set ID.
# string[] set_memberships


# ID of the template used in an agent's knowledge base.
# string id

# A prolog query to submit to the database where the variable `A` is used to match 
# modelets (atoms) that could be alternatives.
string query
